apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectlbot-clusterrole-bind
subjects:
- kind: ServiceAccount
  name: kubectlbot-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: system:kubectlbot
  apiGroup: rbac.authorization.k8s.io